// Mocks generated by Mockito 5.4.5 from annotations
// in interview_task_rapid/test/widgets/task_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:interview_task_rapid/models/task.dart' as _i2;
import 'package:interview_task_rapid/services/task_service.dart' as _i3;
import 'package:interview_task_rapid/view_models/task_view_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i3.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Task> createTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createTask, [task])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Stream<List<_i2.Task>> getUserTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTasks, [userId]),
            returnValue: _i4.Stream<List<_i2.Task>>.empty(),
          )
          as _i4.Stream<List<_i2.Task>>);

  @override
  _i4.Stream<List<_i2.Task>> getSharedTasks(String? userEmail) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedTasks, [userEmail]),
            returnValue: _i4.Stream<List<_i2.Task>>.empty(),
          )
          as _i4.Stream<List<_i2.Task>>);

  @override
  _i4.Future<void> updateTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> shareTask(String? taskId, String? userEmail) =>
      (super.noSuchMethod(
            Invocation.method(#shareTask, [taskId, userEmail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unshareTask(String? taskId, String? userEmail) =>
      (super.noSuchMethod(
            Invocation.method(#unshareTask, [taskId, userEmail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TaskViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskViewModel extends _i1.Mock implements _i5.TaskViewModel {
  MockTaskViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  String get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userEmail),
            ),
          )
          as String);

  @override
  _i4.Stream<List<_i2.Task>> get userTasks =>
      (super.noSuchMethod(
            Invocation.getter(#userTasks),
            returnValue: _i4.Stream<List<_i2.Task>>.empty(),
          )
          as _i4.Stream<List<_i2.Task>>);

  @override
  _i4.Stream<List<_i2.Task>> get sharedTasks =>
      (super.noSuchMethod(
            Invocation.getter(#sharedTasks),
            returnValue: _i4.Stream<List<_i2.Task>>.empty(),
          )
          as _i4.Stream<List<_i2.Task>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> createTask({
    required String? title,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #title: title,
              #description: description,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> shareTask(String? taskId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#shareTask, [taskId, email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unshareTask(String? taskId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#unshareTask, [taskId, email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
